# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Valeska Canales Pozo
site_url: https://github.com/vcanalesp/portafolio
site_author: Valeska Canales
site_description:

# Repository
repo_name: vcanalesp/portafolio
repo_url: https://github.com/vcanalesp/portafolio
edit_uri: ''

# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.projects

extra_css:
  - css/neoteroi-mkdocs.css

# Theme
theme:
  name: dracula
  language: es
  logo: images/yo2.png
  favicon: images/logo_sn.png


# Plugins
plugins:
  - search

 #TOC
nav:
    - 🏠 Home: index.md
    - 👑 Sobre Mí:
      - Presentación: about_me/me.md
      - Educación:  about_me/education.md
      - Experiencia:  about_me/work_exp.md
      - Más Info:  about_me/awards.md
    - 🚀️ Portafolio:
      - Charlas y más: research/talks.md
      - Proyectos:  projects/index.md







